"""Compatibility shim. Canonical module: engine.shared.gates"""

from engine.shared.gates import *  # noqa: F403
from engine.shared.gates import (  # noqa: F401
    BOUNCE_AGAINST_SPY,
    CATASTROPHIC_OPTION_USD,
    CATASTROPHIC_SPY,
    CONSECUTIVE_FAIL_HALT,
    EXTRA_BTO_MFE_USD,
    FAIL_SEC,
    OPEN_REVERSAL_WINDOW,
    PROTECTIVE_STOP_USD,
    QUOTE_GRACE_SEC,
    RISK_QTY_CAP,
    SESSION_LOSS_HALT_USD,
    SESSION_STARTER_CAP,
    STARTER_NOTIONAL_USD,
    TICKET_RISK_USD,
    Direction,
    EnvelopeReason,
    HaltReason,
    SessionState,
    bounce_against,
    decide_manage,
    decide_starter,
    envelope_hit,
    hhmm_in_window,
    ledger_invariant,
    ledger_ok_placeholder,
    new_session,
    starter_qty,
    stc_ladder_prices,
    unrealized_dollars,
)
